# Salary Analysis - Data Preparing

### Importing Libraries

In [1]:
import pandas as pd
import numpy as np

### Reading the csv files

In [2]:
# Fetching only the header row
df_col = pd.read_csv('stack_overflow_data.csv', nrows=0)

In [3]:
df_col.shape

(0, 172)

In [4]:
# columns with different columns (taken from prev warning)
flagged_col=[56,74,92,97,98,105,109,110,132,162,165]

for i in flagged_col:
    print(i,'-',df_col.columns[i])

56 - JobSatPoints_15_TEXT
74 - DatabaseHaveEntry
92 - DevEnvHaveEntry
97 - SOTagsHaveEntry
98 - SOTagsWant Entry
105 - OfficeStackWantEntry
109 - CommPlatformHaveEntr
110 - CommPlatformWantEntr
132 - SO_Actions_15_TEXT
162 - AIAgentOrchestration
165 - AIAgentObsWrite

In [5]:
# reading the file at once and not in chunks, no datatype assumption
df = pd.read_csv('stack_overflow_data.csv', low_memory = False)

In [6]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [7]:
df.shape

(49191, 172)

In [8]:
for i in flagged_col:
    col=df_col.columns[i]
    print(col, ':',df[col].apply(type).value_counts())

JobSatPoints_15_TEXT : <class 'float'>    48527
<class 'str'>        664
Name: JobSatPoints_15_TEXT, dtype: int64
DatabaseHaveEntry : <class 'float'>    47040
<class 'str'>       2151
Name: DatabaseHaveEntry, dtype: int64
DevEnvHaveEntry : <class 'float'>    46429
<class 'str'>       2762
Name: DevEnvHaveEntry, dtype: int64
SOTagsHaveEntry : <class 'float'>    48731
<class 'str'>        460
Name: SOTagsHaveEntry, dtype: int64
SOTagsWant Entry : <class 'float'>    48759
<class 'str'>        432
Name: SOTagsWant Entry, dtype: int64
OfficeStackWantEntry : <class 'float'>    47571
<class 'str'>       1620
Name: OfficeStackWantEntry, dtype: int64
CommPlatformHaveEntr : <class 'float'>    47712
<class 'str'>       1479
Name: CommPlatformHaveEntr, dtype: int64
CommPlatformWantEntr : <class 'float'>    48004
<class 'str'>       1187
Name: CommPlatformWantEntr, dtype: int64
SO_Actions_15_TEXT : <class 'float'>    48365
<class 'str'>        826
Name: SO_Actions_15_TEXT, dtype: int64
AIAgentOrchestration : <class 'float'>    45431
<class 'str'>       3760
Name: AIAgentOrchestration, dtype: int64
AIAgentObsWrite : <class 'float'>    48922
<class 'str'>        269
Name: AIAgentObsWrite, dtype: int64

All flagged_cols with different datatype are not relevant for data analysis purpose, that's why no need to take action

### Data Cleaning

#### Removing extra columns

In [9]:
# columns actually helping with our analysis
col_needed=['EdLevel','WorkExp','DevType', 'OrgSize','RemoteWork', 'Country',
            'LanguageHaveWorkedWith','ConvertedCompYearly']

In [10]:
df_small=df[col_needed].copy()

In [11]:
df_small.head()

,EdLevel,WorkExp,DevType,OrgSize,RemoteWork,Country,LanguageHaveWorkedWith,ConvertedCompYearly
0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",8.0,"Developer, mobile",20 to 99 employees,Remote,Ukraine,Bash/Shell (all shells);Dart;SQL,61256.0
1,"Associate degree (A.A., A.S., etc.)",2.0,"Developer, back-end",500 to 999 employees,"Hybrid (some in-person, leans heavy to flexibi...",Netherlands,Java,104413.0
2,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",10.0,"Developer, front-end",NaN,NaN,Ukraine,Dart;HTML/CSS;JavaScript;TypeScript,53061.0
3,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",4.0,"Developer, back-end","10,000 or more employees",Remote,Ukraine,Java;Kotlin;SQL,36197.0
4,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",21.0,Engineering manager,NaN,NaN,Ukraine,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,60000.0

In [75]:
df_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EdLevel                 48149 non-null  object
 1   WorkExp                 42893 non-null  float64
 2   DevType                 43680 non-null  object
 3   OrgSize                 34178 non-null  object
 4   RemoteWork              33780 non-null  object
 5   Country                 35437 non-null  object
 6   LanguageHaveWorkedWith  31671 non-null  object
 7   ConvertedCompYearly     23947 non-null  float64
dtypes: float64(2), object(6)
memory usage: 3.0+ MB

##### Filtering out only the USA data

In [12]:
# filtering out US country data only
data = df_small[df_small['Country']=='United States of America'].copy()

In [13]:
data.head(2)

,EdLevel,WorkExp,DevType,OrgSize,RemoteWork,Country,LanguageHaveWorkedWith,ConvertedCompYearly
21,Some college/university study without earning ...,35.0,Academic researcher,I don’t know,"Your choice (very flexible, you can come in wh...",United States of America,Assembly;Bash/Shell (all shells);C;C++;Fortran...,NaN
22,Some college/university study without earning ...,7.0,"Developer, full-stack",100 to 499 employees,Remote,United States of America,C#;C++;JavaScript;Python;Visual Basic (.Net),87500.0

#### Treating ConvertedCompYearly Column

##### Removing rows containing NULL values

In [14]:
data['ConvertedCompYearly'].isnull().sum()

1990

In [15]:
# now dropping ConvertedCompYearly wherever we find NULL in ConvertedCompYearly
# ConvertedCompYearly will be corrupted if we try to imute them
data=data.dropna(subset=['ConvertedCompYearly'])

In [16]:
data['ConvertedCompYearly'].isnull().sum()

0

##### Statistical Analysis

In [17]:
data['ConvertedCompYearly'].describe()

count    5.243000e+03
mean     1.798045e+05
std      7.123180e+05
min      1.000000e+00
25%      1.010000e+05
50%      1.500000e+05
75%      2.000000e+05
max      5.000000e+07
Name: ConvertedCompYearly, dtype: float64

In [18]:
data['ConvertedCompYearly'].quantile([0.01, 0.05, 0.95, 0.99])

0.01       235.88
0.05     35000.00
0.95    350000.00
0.99    650000.00
Name: ConvertedCompYearly, dtype: float64

##### Removing Garbage values

In [19]:
# Filtered to the 5th-99th percentile range based on percentile-jump analysis
# — values below $35K and above $650K showed disproportionate jumps versus 
# adjacent percentiles, indicating likely data entry errors rather than genuine salaries.

df_clean=data[(data['ConvertedCompYearly']>=35000.00) & 
              (data['ConvertedCompYearly']<=650000.00)]

In [20]:
df_clean.shape

(4934, 8)

In [21]:
df_clean['ConvertedCompYearly'].describe()

count      4934.000000
mean     167929.464734
std       89330.625116
min       35000.000000
25%      110000.000000
50%      150000.000000
75%      200000.000000
max      650000.000000
Name: ConvertedCompYearly, dtype: float64

#### Treating WorkExp Column

In [22]:
df_clean['WorkExp'].isnull().sum()

43

In [23]:
# dropping null values row because fraction for NULL values is very less, almost 0.88%
df_clean=df_clean.dropna(subset=['WorkExp']).copy()

In [24]:
df_clean['WorkExp'].isnull().sum()

0

In [25]:
df_clean['WorkExp'].describe()

count    4891.000000
mean       16.607851
std        10.997284
min         1.000000
25%         8.000000
50%        15.000000
75%        24.000000
max        61.000000
Name: WorkExp, dtype: float64

In [26]:
df_clean['WorkExp'].quantile([0.01,0.05,0.95,0.99])

0.01     1.0
0.05     2.0
0.95    38.0
0.99    45.0
Name: WorkExp, dtype: float64

#### Treating LanguageHaveWorkedWith Column

In [27]:
df_clean['LanguageHaveWorkedWith'].isnull().sum()

236

In [28]:
df_clean = df_clean.dropna(subset=['LanguageHaveWorkedWith']).copy()

In [29]:
df_clean['LanguageHaveWorkedWith'].isnull().sum()

0

In [30]:
df_clean.shape

(4655, 8)

Separating the top languages for new binary columns

In [31]:
df_clean['LanguageHaveWorkedWith'].iloc[0]

'C#;C++;JavaScript;Python;Visual Basic (.Net)'

In [32]:
# all language in a list
all_languages = df_clean['LanguageHaveWorkedWith'].dropna().str.split(';').explode()
# frequency for every language
lang_counts = all_languages.value_counts()

In [33]:
lang_counts

JavaScript                 3276
SQL                        3017
HTML/CSS                   2997
Python                     2893
Bash/Shell (all shells)    2601
TypeScript                 2172
C#                         1564
PowerShell                 1345
Java                       1243
C++                         999
C                           910
Go                          887
Rust                        722
PHP                         641
Ruby                        469
Kotlin                      429
Lua                         411
Swift                       293
Visual Basic (.Net)         270
R                           264
Groovy                      255
Assembly                    242
Perl                        237
VBA                         222
Elixir                      151
MATLAB                      150
Dart                        150
GDScript                    145
Scala                       132
Lisp                        131
MicroPython                 105
Zig                          95
Erlang                       75
Fortran                      65
Delphi                       58
F#                           50
Gleam                        45
OCaml                        41
COBOL                        37
Ada                          32
Prolog                       25
Mojo                          8
Name: LanguageHaveWorkedWith, dtype: int64

We will take only top 5% languages (frequency>=233) => approx 21 languages

In [34]:
threshold = 0.05 * len(df_clean)

In [35]:
# we want only the index values from the lang_counts
top_lang = lang_counts[lang_counts>=threshold].index.tolist()

##### Creating new Binary Language Columns

In [36]:
for lang in top_lang:
    df_clean[f'lang_{lang}'] = df_clean['LanguageHaveWorkedWith'].apply(
    lambda x: 1 if lang in x.split(';') else 0
    )

In [37]:
def other_lang(x):
    language = x.split(';')
    return 1 if any(lang not in top_lang for lang in language) else 0


df_clean['lang_others'] = df_clean['LanguageHaveWorkedWith'].apply(other_lang)

In [38]:
df_clean.head(2)

,EdLevel,WorkExp,DevType,OrgSize,RemoteWork,Country,LanguageHaveWorkedWith,ConvertedCompYearly,lang_JavaScript,lang_SQL,...,lang_Ruby,lang_Kotlin,lang_Lua,lang_Swift,lang_Visual Basic (.Net),lang_R,lang_Groovy,lang_Assembly,lang_Perl,lang_others
22,Some college/university study without earning ...,7.0,"Developer, full-stack",100 to 499 employees,Remote,United States of America,C#;C++;JavaScript;Python;Visual Basic (.Net),87500.0,1,0,...,0,0,0,0,1,0,0,0,0,0
29,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",19.0,"Developer, mobile",500 to 999 employees,Remote,United States of America,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,205000.0,1,1,...,0,1,0,1,0,0,0,0,0,0

In [39]:
df_clean[[f'lang_{lang}' for lang in top_lang]].sum()

lang_JavaScript                 3276
lang_SQL                        3017
lang_HTML/CSS                   2997
lang_Python                     2893
lang_Bash/Shell (all shells)    2601
lang_TypeScript                 2172
lang_C#                         1564
lang_PowerShell                 1345
lang_Java                       1243
lang_C++                         999
lang_C                           910
lang_Go                          887
lang_Rust                        722
lang_PHP                         641
lang_Ruby                        469
lang_Kotlin                      429
lang_Lua                         411
lang_Swift                       293
lang_Visual Basic (.Net)         270
lang_R                           264
lang_Groovy                      255
lang_Assembly                    242
lang_Perl                        237
dtype: int64

In [40]:
df_clean['lang_others'].sum()

1249

For checking if the frequency still match with previous lang_counts

#### Checking other columns

In [41]:
df_clean.head(2)

,EdLevel,WorkExp,DevType,OrgSize,RemoteWork,Country,LanguageHaveWorkedWith,ConvertedCompYearly,lang_JavaScript,lang_SQL,...,lang_Ruby,lang_Kotlin,lang_Lua,lang_Swift,lang_Visual Basic (.Net),lang_R,lang_Groovy,lang_Assembly,lang_Perl,lang_others
22,Some college/university study without earning ...,7.0,"Developer, full-stack",100 to 499 employees,Remote,United States of America,C#;C++;JavaScript;Python;Visual Basic (.Net),87500.0,1,0,...,0,0,0,0,1,0,0,0,0,0
29,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",19.0,"Developer, mobile",500 to 999 employees,Remote,United States of America,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,205000.0,1,1,...,0,1,0,1,0,0,0,0,0,0

##### EdLevel

In [42]:
df_clean['EdLevel'].isnull().sum()

3

In [43]:
df_clean = df_clean.dropna(subset=['EdLevel'])

In [44]:
df_clean['EdLevel'].isnull().sum()

0

In [45]:
df_clean['EdLevel'].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          2550
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        951
Some college/university study without earning a degree                                 552
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         254
Associate degree (A.A., A.S., etc.)                                                    220
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     100
Other (please specify):                                                                 13
Primary/elementary school                                                               12
Name: EdLevel, dtype: int64

##### DevType

In [46]:
df_clean['DevType'].isnull().sum()

0

In [47]:
devType_all = df_clean['DevType'].value_counts()
devType_all

Developer, full-stack                            1551
Developer, back-end                               626
Architect, software or solutions                  300
Developer, desktop or enterprise applications     243
Engineering manager                               205
Developer, front-end                              186
Other (please specify):                           173
Developer, embedded applications or devices       163
DevOps engineer or professional                   137
Developer, mobile                                 111
Data engineer                                     110
Data scientist                                     86
Academic researcher                                80
Cloud infrastructure engineer                      72
Senior executive (C-suite, VP, etc.)               72
AI/ML engineer                                     71
System administrator                               55
Cybersecurity or InfoSec professional              53
Applied scientist                                  50
Data or business analyst                           41
Developer, QA or test                              39
Founder, technology or otherwise                   39
Product manager                                    30
Support engineer or analyst                        29
Developer, game or graphics                        27
Database administrator or engineer                 23
Project manager                                    19
Student                                            16
Developer, AI apps or physical AI                  15
Retired                                            14
Financial analyst or engineer                      10
UX, Research Ops or UI design professional          6
Name: DevType, dtype: int64

Note that Student, Retired are not professional roles, removing them as well as profession with lower frequency

In [48]:
threshold = 100

In [49]:
top_devType_all = devType_all[devType_all>=threshold].index.tolist()

In [50]:
top_devType_all

['Developer, full-stack',
 'Developer, back-end',
 'Architect, software or solutions',
 'Developer, desktop or enterprise applications',
 'Engineering manager',
 'Developer, front-end',
 'Other (please specify):',
 'Developer, embedded applications or devices',
 'DevOps engineer or professional',
 'Developer, mobile',
 'Data engineer']

In [51]:
role_to_keep = ['Data scientist', 'AI/ML engineer', 'Data or business analyst']

top_devType_all = list(set(top_devType_all + role_to_keep))
top_devType_all

['Other (please specify):',
 'Developer, front-end',
 'Engineering manager',
 'Data engineer',
 'Developer, mobile',
 'AI/ML engineer',
 'Architect, software or solutions',
 'Developer, embedded applications or devices',
 'Developer, full-stack',
 'Data scientist',
 'Data or business analyst',
 'Developer, desktop or enterprise applications',
 'DevOps engineer or professional',
 'Developer, back-end']

In [52]:
final_devType = [role for role in top_devType_all if 'Other' not in role]
final_devType

['Developer, front-end',
 'Engineering manager',
 'Data engineer',
 'Developer, mobile',
 'AI/ML engineer',
 'Architect, software or solutions',
 'Developer, embedded applications or devices',
 'Developer, full-stack',
 'Data scientist',
 'Data or business analyst',
 'Developer, desktop or enterprise applications',
 'DevOps engineer or professional',
 'Developer, back-end']

In [53]:
df_clean['DevType_grouped'] = df_clean['DevType'].apply(
                                lambda x: x if x in final_devType else 'Other'
                                )

In [54]:
df_clean['DevType_grouped'].value_counts()

Developer, full-stack                            1551
Other                                             822
Developer, back-end                               626
Architect, software or solutions                  300
Developer, desktop or enterprise applications     243
Engineering manager                               205
Developer, front-end                              186
Developer, embedded applications or devices       163
DevOps engineer or professional                   137
Developer, mobile                                 111
Data engineer                                     110
Data scientist                                     86
AI/ML engineer                                     71
Data or business analyst                           41
Name: DevType_grouped, dtype: int64

##### OrgSize

In [55]:
df_clean['OrgSize'].isnull().sum()

339

In [56]:
df_clean['OrgSize'].value_counts()

10,000 or more employees                              982
100 to 499 employees                                  820
20 to 99 employees                                    707
1,000 to 4,999 employees                              611
Less than 20 employees                                458
500 to 999 employees                                  307
5,000 to 9,999 employees                              261
Just me - I am a freelancer, sole proprietor, etc.     87
I don’t know                                           80
Name: OrgSize, dtype: int64

Analysing NULL values (if they are same as `I don't know category` or values left from filling)
* if similar stats merge null values in `I don't know` category

In [57]:
nulls = df_clean[df_clean['OrgSize'].isnull()]

nulls['ConvertedCompYearly'].describe()

count       339.000000
mean     157052.672566
std       98592.253838
min       35000.000000
25%      100000.000000
50%      140000.000000
75%      196200.000000
max      650000.000000
Name: ConvertedCompYearly, dtype: float64

In [58]:
df_temp = df_clean[df_clean['OrgSize'] == 'I don’t know']
df_temp['ConvertedCompYearly'].describe()

count        80.000000
mean     139445.537500
std       63363.017023
min       35000.000000
25%       95000.000000
50%      130000.000000
75%      170500.000000
max      350000.000000
Name: ConvertedCompYearly, dtype: float64

In [59]:
from scipy import stats

null_salary = df_clean[df_clean['OrgSize'].isnull()]['ConvertedCompYearly']
dontknow_salary = df_clean[df_clean['OrgSize'] == 'I don’t know']['ConvertedCompYearly']

t_stat, p_value = stats.ttest_ind(null_salary, dontknow_salary, equal_var=False)
print(f"t-statistic: {t_stat:.3f}, p-value: {p_value:.4f}")

t-statistic: 1.983, p-value: 0.0489

T-test
* p_value > 0.05 => same groups
* p_value < 0.05 => different groups

p-value > 0.05 => two different population (well our p-value is approx 0.05 but we have huge difference between both mean as well) => Assign New group

The null values doesn't belongs to 'I don’t know'category. That's why imputing the null values with a unknown group.

In [60]:
df_clean['OrgSize'] = df_clean['OrgSize'].fillna('Unknown')

In [61]:
df_clean['OrgSize'].value_counts()

10,000 or more employees                              982
100 to 499 employees                                  820
20 to 99 employees                                    707
1,000 to 4,999 employees                              611
Less than 20 employees                                458
Unknown                                               339
500 to 999 employees                                  307
5,000 to 9,999 employees                              261
Just me - I am a freelancer, sole proprietor, etc.     87
I don’t know                                           80
Name: OrgSize, dtype: int64

##### RemoteWork

In [62]:
df_clean['RemoteWork'].isnull().sum()

350

In [63]:
df_clean['RemoteWork'].value_counts()

Remote                                                                          2016
Hybrid (some remote, leans heavy to in-person)                                   732
In-person                                                                        604
Hybrid (some in-person, leans heavy to flexibility)                              571
Your choice (very flexible, you can come in when you want or just as needed)     379
Name: RemoteWork, dtype: int64

In [64]:
df_clean['RemoteWork'] = df_clean['RemoteWork'].fillna('Unknown')

In [65]:
df_clean['RemoteWork'].isnull().sum()

0

In [66]:
df_clean['RemoteWork'].value_counts()

Remote                                                                          2016
Hybrid (some remote, leans heavy to in-person)                                   732
In-person                                                                        604
Hybrid (some in-person, leans heavy to flexibility)                              571
Your choice (very flexible, you can come in when you want or just as needed)     379
Unknown                                                                          350
Name: RemoteWork, dtype: int64

In [76]:
df_clean.shape

(4652, 33)

In [67]:
df_clean.to_csv('cleaned_survey_data.csv', index=False)

#### Preparing to export data to database

In [68]:
# resetting index
df_clean = df_clean.reset_index(drop=True).copy()  # wipes old index entirely, generates fresh clean 0,1,2...

In [69]:
df_clean.head(2)

,EdLevel,WorkExp,DevType,OrgSize,RemoteWork,Country,LanguageHaveWorkedWith,ConvertedCompYearly,lang_JavaScript,lang_SQL,...,lang_Kotlin,lang_Lua,lang_Swift,lang_Visual Basic (.Net),lang_R,lang_Groovy,lang_Assembly,lang_Perl,lang_others,DevType_grouped
0,Some college/university study without earning ...,7.0,"Developer, full-stack",100 to 499 employees,Remote,United States of America,C#;C++;JavaScript;Python;Visual Basic (.Net),87500.0,1,0,...,0,0,0,1,0,0,0,0,0,"Developer, full-stack"
1,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",19.0,"Developer, mobile",500 to 999 employees,Remote,United States of America,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,205000.0,1,1,...,1,0,1,0,0,0,0,0,0,"Developer, mobile"

Respondent data

In [70]:
data_respondent = df_clean[['ConvertedCompYearly', 'EdLevel', 'WorkExp',
                           'DevType_grouped','OrgSize','RemoteWork','Country']].copy()

data_respondent.columns = ['salary_usd', 'ed_level', 'work_exp',
                           'dev_type','org_size','remote_work','country']

# data_respondent = data_respondent.reset_index(drop=True)  # wipes old index entirely, generates fresh clean 0,1,2...
data_respondent.index.name = 'respondent_id'
data_respondent = data_respondent.reset_index().copy()

In [71]:
data_respondent.head(2)

,respondent_id,salary_usd,ed_level,work_exp,dev_type,org_size,remote_work,country
0,0,87500.0,Some college/university study without earning ...,7.0,"Developer, full-stack",100 to 499 employees,Remote,United States of America
1,1,205000.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",19.0,"Developer, mobile",500 to 999 employees,Remote,United States of America

In [72]:
data_respondent.columns

Index(['respondent_id', 'salary_usd', 'ed_level', 'work_exp', 'dev_type',
       'org_size', 'remote_work', 'country'],
      dtype='object')

Language data

In [73]:
lang_cols = [c for c in df_clean.columns if c.startswith('lang_')]

data_language = []

for idx, rows in df_clean.iterrows():
    for col in lang_cols:
        if rows[col] == 1:
            data_language.append({'respondent_id':idx, 'language': col.replace('lang_','')})

In [73]:
respondent_language = pd.DataFrame(data_language)

In [74]:
respondent_language.head(2)

   respondent_id    language
0              0  JavaScript
1              0      Python